name: CI/CD to Huawei SWR and CCE

on:
  push:
    branches:
      - master  # Trigger CI/CD when code is pushed to the 'master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker buildx build -t hello .

      - name: Log in to Huawei Cloud SWR
        uses: huaweicloud/swr-login@v2.1.0
        with:
          access-key-id: ${{ secrets.ACCESSKEY }}
          access-key-secret: ${{ secrets.SECRETACCESSKEY }}
          region: af-south-1

      - name: Build and push Docker image
        run: |
          docker build -t swr.af-south-1.myhuaweicloud.com/credpal/corporate-loans:${{ github.sha }} .
          docker push swr.af-south-1.myhuaweicloud.com/credpal/corporate-loans:${{ github.sha }}

      - name: Configure kubectl for Huawei CCE
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > kubeconfig.yaml
          kubectl config view --kubeconfig=kubeconfig.yaml
          kubectl config get-contexts --kubeconfig=kubeconfig.yaml
          kubectl config use-context external --kubeconfig=kubeconfig.yaml
          kubectl config current-context --kubeconfig=kubeconfig.yaml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure kubectl for Huawei CCE
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > kubeconfig.yaml
          kubectl config view --kubeconfig=kubeconfig.yaml
          kubectl config get-contexts --kubeconfig=kubeconfig.yaml
          kubectl config use-context external --kubeconfig=kubeconfig.yaml
          kubectl config current-context --kubeconfig=kubeconfig.yaml

      - name: Debugging
        run: |
          kubectl config current-context
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy to Huawei CCE
        run: |
          kubectl create deployment my-app-deployment --image=${{ secrets.HUAWEI_SWR_REGISTRY }}/hello-world-nodejs:latest --dry-run=client -o yaml | kubectl apply -f -
          kubectl set image deployment/my-app-deployment my-app=${{ secrets.HUAWEI_SWR_REGISTRY }}/hello-world-nodejs:latest
